import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { SanityLive } from "@/sanity/lib/live";
import { Toaster } from "react-hot-toast";
import { VisualEditing } from "next-sanity/visual-editing";
import { draftMode } from "next/headers";
import DisableDraftMode from "@/components/DisableDraftMode";
import ChatIcon from "@/components/ChatIcon";

export const metadata: Metadata = {
  title: "P3D",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen bg-linear-to-br from-background via-muted/30 to-background">
      {(await draftMode()).isEnabled && (
        <>
          <DisableDraftMode />
          <VisualEditing />
        </>
      )}
      <Header />
      <main className="relative">{children}</main>
      <Footer />
      <Toaster
        position="bottom-right"
        toastOptions={{
          style: {
            background: "#1d1145",
            color: "#fff",
          },
        }}
      />
      <SanityLive />
      <ChatIcon />
    </div>
  );
}
