import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Ecommerce Backend",
  description: "Generated by create next app",
};

const StudioLayout = ({ children }: { children: React.ReactNode }) => {
  return <>{children}</>;
};

export default StudioLayout;
